scalameta/nvim-metals

README.md
doc/metals.txt
nvim-lsp.vim
plugin/metals.vim

Previously these were just examples, but I figured I'd just add them in
and expose them for easier usage.

Add in metals#warnings() and metals#errors().

---

lua/metals.lua
lua/metals/setup.lua
lua/metals/util.lua
nvim-lsp.vim
plugin/metals.vim

Instead of taking the color from metals options the color is configurable.
It doesn't include the hover messages. I've created a separate issue to discuss this behaviour.

Support the Decoration Protocol #4

---

README.md
doc/metals.txt
lua/metals.lua
lua/metals/decoration.lua
lua/metals/setup.lua
lua/metals/util.lua
nvim-lsp.vim

Add in ability to expand decorations

---

lua/metals/diagnostic.lua

PR for https://github.com/scalameta/nvim-metals/issues/31

#31 GetAll diagnostics as per new LSP

---

lua/metals/handlers.lua

The one that is in core has a bug, so for the time being we'll overwrite it.
There is a pr to fix this, so it should be quite temporary

Revert and add back in showMessageRequest

---

README.md
doc/metals.txt
lua/metals/handlers.lua

This is now fixed upstream so we can remove it here.

Remove showMessageRequest now that fix is merged.

---

.gitignore
autoload/health/metals.vim
lua/metals/health.lua
lua/metals/setup.lua

Add in basic checkhealth

---

doc/metals.txt
lua/metals.lua
lua/metals/ui.lua

This will work more nicely when https://github.com/scalameta/metals/pull/2393 is merged.

Add a ui module and make info display in a floating window

---

lua/metals.lua
lua/metals/health.lua
lua/metals/util.lua

I didn't realize that vim.fn.system will do literally
the same thing. I should just use this.

Get rid of os_capture command.

---

.luacheckrc
lua/metals/log.lua
lua/metals/setup.lua

This change ensures that when a user is using `:MetalsInstall` it doesn't block.
Another addition is adding in  https://github.com/tjdevries/vlog.nvim which introduces
nvim-metals specific logging. I plan to actually overhaul this a bit for my needs, but
this just introduces it.
Closes #71
Closes #65

Change install to use vim.loop.spawn.

---

README.md
doc/metals.txt

Make sure it's super clear that using metalsStatus is preferable. I also
make a list of all the settings to easily see an overview.
Closes #79

Add in more docs about status.

---

lua/metals/decoration.lua
lua/metals/handlers.lua
lua/metals/setup.lua
lua/metals/ui.lua
lua/metals/util.lua

- Also move the wrap_hover function out of the util module and into the ui module.
- Also re-use the path utils instead of checking for files manually
Closes #76

Make a metals_status util function.

---

lua/metals.lua
lua/metals/handlers.lua

Add in logging to missing places.

---

doc/metals.txt
lua/metals.lua
lua/metals/log.lua
lua/metals/setup.lua
lua/metals/util.lua

See individual commits for details.
Addresses some parts of https://github.com/scalameta/nvim-metals/issues/81

More info in `:MetalsInfo`

---

doc/metals.txt
lua/metals.lua
lua/metals/handlers.lua
lua/metals/log.lua
lua/metals/messages.lua
lua/metals/setup.lua

There were large parts of log.lua that weren't being used, and I wanted to be able
to log and show something with one call, but not all the time. This introduced a new
log api that allows you to do log.info() and also provides a log.info_and_show() which
will both log and show the user. The same for warning and error.
I also replaced all usages of print with this in various places. This may be a bit excessive
in logging, but we'll see.
Closes #78

Refactor log.lua.

---

doc/metals.txt
lua/metals.lua
lua/metals/ui.lua

Instead of the semi-transparent window that is hard to see and looks
ugly, replace the UI module with one that creates windows based on
content size, but still centered in the screen. Plus, it adds a nice
border and a title to that border. This will hopefully unlock other
better UI stuff with windows.

Refactor UI module.

---

doc/metals.txt
lua/metals/doctor.lua
lua/metals/handlers.lua
lua/metals/setup.lua
lua/metals/ui.lua
lua/metals/util.lua

Add in embedded doctor

---

lua/metals.lua
lua/metals/setup.lua

Relates to #81 
I also put in `filetypes` in the config table just to make sure users won't hit on this if they are using `lspsaga`: https://github.com/glepnir/lspsaga.nvim/issues/57

Add in settings to MetalsInfo

---

doc/metals.txt

This is a setting introduced here: https://github.com/scalameta/metals/pull/2417

Add in fallbackScalaVersion setting.

---

lua/metals/setup.lua

Add fallbackScalaVersion into the settings table to be checked against

---

README.md
doc/metals.txt
lua/metals.lua
lua/metals/setup.lua

~This introduces three new basic commands. `:MetalsRun`, `:MetalsTestFile`, and `:MetalsTestTarget`. The majority of the changes needed to make this work are actual in the server itself. I'll have a pr open for that soon, but this is the base of how I'm testing it.~
See the comments down below for updates
Closes #57

Basic nvim-dap integration

---

lua/metals/diagnostic.lua
lua/metals/handlers.lua
lua/metals/setup.lua

We also check to ensure there is a res when we are sending in the debug
request to metals.

Handle metals-diagnostic-focus

---

.github/workflows/ci.yml
lua/metals.lua
lua/metals/handlers.lua
lua/metals/health.lua
lua/metals/log.lua
lua/metals/setup.lua
lua/metals/ui.lua
lua/metals/util.lua

Now that the new version of stylua is out, a bug with iife is fixed, so
we don't need to ignore util.lua anymore

Remove format filter for util

---

lua/metals/setup.lua
plugin/metals.vim

This will no only actual register them when the initialize_or_attach is
called.

Make sure metals commands don't bleed out when we aren't using Metals.

---

doc/metals.txt

fixed typos in documentation

---

.github/workflows/ci.yml
CONTRIBUTING.md
Makefile
lua/metals.lua
lua/metals/doctor.lua
lua/metals/handlers.lua
lua/metals/setup.lua

Also make sure we target that version in CI

Bump to newest stylua.

---

lua/metals/tvp/init.lua

I also separate the logic out into a function that we can also use in
toggle_tree.

Add a check in so a user can't reveal in tree before tree exists.

---

doc/metals.txt
lua/metals.lua
lua/metals/commands.lua

Behind the scenes this does the exact same thing as `MetalsInstall`, but
just takes any confusion out of whether or not you should do `Install`
to also update.

Add in a `MetalsUpdate` command.

---

doc/metals.txt
lua/metals.lua
lua/metals/commands.lua
lua/metals/setup.lua

Once https://github.com/neovim/neovim/pull/13165 is merged we can finish this up.

Add commands in to test code lenses

---

lua/metals/tvp/init.lua

Previously we wouldn't jump the user into the actual tree window if it
was already open. We now ensure that it's open and then move the user
there.
Closes #148

[Bugfix] - Ensure reveal in tree works if tree is already open.

---

lua/metals/setup.lua

Ensure autocmds are fired correctly

---

doc/metals.txt

Changed introduction section from metals-introdction to metals-introduction

fix introduction section typo

---

doc/metals.txt

- fixed links to documentation
- fixed typos
- (optional) tried to make common syntax for lua require("")

fix typos, lua require style and link to documentation

---

.github/workflows/ci.yml
README.md

I will still keep this compatible with 0.5.0, and if need
be will add in checks in the code. I just don't want to maintain two branches.

Get rid of the next branch.

---

lua/metals/setup.lua

@lewis6991 much better idea. Regarding
> Do we need to also update the autocmds so the relevant ones are buffer local?
I don't _believe_ this should be an issue, but which ones did you have in mind?

Ensure scala file is on disk

---

lua/metals.lua
lua/metals/setup.lua

Fix bug where metals.lua doesn't see config changes

---

lua/metals.lua
lua/metals/setup.lua

Ensure the settings cache can be picked up by metals.lua

---

lua/metals.lua
lua/metals/handlers.lua
lua/metals/tvp/init.lua
lua/metals/util.lua

When https://github.com/neovim/neovim/pull/15504 is merged in the
handler signatures will change. This will allow for that change while
also continuing to work with 0.5.

Prepare for upcoming handler changes.

---

lua/metals/util.lua

Fix handlers when they are wrapped

---

lua/metals.lua
lua/metals/commands.lua
lua/metals/handlers.lua

Needed for the upcoming https://github.com/scalameta/metals/pull/3063

Basic framework for the show tasty command.

---

lua/metals.lua
lua/metals/commands.lua
lua/metals/decoder.lua
lua/metals/handlers.lua

NOTE: The above is still an issue, but only in the situation where the package structure on disk doesn't match the package structure you actually have in place.
- https://github.com/scalameta/metals/issues/3150
- https://github.com/scalameta/metals/issues/3136

Javap semanticdb command support

---

doc/metals.txt
lua/metals.lua
lua/metals/commands.lua
lua/metals/decoder.lua

https://github.com/scalameta/metals/pull/3247

Changes needed for cfr support.

---

doc/metals.txt
lua/metals/config.lua
lua/metals/decoration.lua
lua/metals/handlers.lua

Instead of using the old way to set the decorations color with g['metals_decoration_color']
it's now preferable to set it with decorationColor in your settings config table

Migrate metals_decoration_color to setup table.

---

CONTRIBUTING.md
README.md
doc/metals.txt
lua/metals.lua
lua/metals/handlers.lua
lua/metals/install.lua

This also removes usage of 'simply'

Add in reference to feature list.

---

lua/metals/tvp/init.lua

fix: ensure params are created before we jump to the tvp window

---

doc/metals.txt
lua/metals.lua
lua/metals/config.lua
lua/metals/install.lua
lua/metals/messages.lua
lua/metals/setup.lua

This is a breaking change. Please see https://github.com/scalameta/nvim-metals/discussions/253#discussioncomment-1750274 for more info.

Remove deprecated options.

---

lua/metals.lua
lua/metals/doctor.lua

Opinionated, but hey, I like it.
We can try to make this more configurable if people complain.

refactor: Make the windows mimic telescope windows

---

doc/metals.txt
lua/metals.lua
lua/metals/commands.lua
lua/metals/config.lua

Closes #307
Accounts for the new features introduced in https://github.com/scalameta/metals/pull/2520

feat: java formatting and new java file command

---

Makefile

fix(ci): try to run tests sequentially

---

lua/metals/log.lua

refactor(log): utilize vim.notify for showing to the user

---

lua/metals/config.lua
lua/metals/doctor.lua
lua/metals/tvp/init.lua
lua/metals/tvp/util.lua
lua/metals/util.lua

This shouldn't change anything for the user, but it tells the server to
not compute doctor related things unless the doctor window is open.

feat: add in doctorVisibilityProvider

---

lua/metals/install.lua

Instead of passing in another job as a callback to the job that gets the
server version use the curl module instead. This makes everything much
cleaner. Now we just curl to get the latest.snapshot, and then do the
normal install job.

refactor: use curl module instead of job callback

---

lua/metals.lua

The gitter link seems return 404. so I removed it and also added discord link in MetalInfo table.

Fix outdated link in MetalInfo

---

doc/metals.txt

`Metals_config` -> `metals_config`

Fix typo in metals.txt

---

doc/metals.txt

docs: add note about javaHome

---

doc/metals.txt
lua/metals.lua
lua/metals/commands.lua
lua/metals/config.lua

This will be added in https://github.com/scalameta/metals/pull/3996.

feat: add support for scalafix-run command

---

lua/metals/tvp/init.lua
lua/metals/tvp/node.lua

Just noticed these while reading the tvp code :)

Fix typos in code comments

---

doc/metals.txt
lua/metals/tvp/init.lua
lua/metals/util.lua

This is how tvp with default icons looks for me:

feat(tvp): add icons

---

lua/metals.lua
lua/metals/setup.lua

Hey! I was looking at some parts of the code and opened #471, and then I was curious about the `vim.lsp.start` call and started playing with it, and since it was pretty straight forward to have it working I've also opened this PR.
Hope it's close to how you was thinking of implementing it :)
Closes #413

feat: migrate to vim.lsp.start

---

lua/metals/status.lua
tests/tests/handlers/status_spec.lua

fix: scape % before setting metals_status

---

lua/metals.lua

Fixes https://github.com/scalameta/nvim-metals/issues/504

fix: open quick worksheet file if it already exists

---

lua/metals/util.lua

No idea what the hell I was thinking here. This made no sense
and I was returning the entire client instead of the actual
buffer like I wanted.

fix: correct mistake in new find_metals_buffer

---

doc/metals.txt
lua/metals.lua
lua/metals/commands.lua

You can read more about this feature in https://scalameta.org/metals/blog/#introducing-error-reports

feat: add in zip reports command

---

doc/metals.txt
lua/metals.lua
lua/metals/commands.lua

closes https://github.com/scalameta/nvim-metals/issues/569.

feat: add support for `metals.scalafix-run-only`

---

doc/metals.txt
lua/metals.lua
lua/metals/commands.lua

refs: https://github.com/scalameta/metals/pull/5060

feat: add in support for reset-workspace

---

lua/metals/config.lua

feat: add in necessary extra javaOpts to allow for Java Hover

---

lua/metals.lua

fix: https://github.com/scalameta/nvim-metals/issues/617

fix: deprecated vim.lsp.util._trim

---

lua/metals/doctor.lua

feat: account for v5 of the Doctor

---

doc/metals.txt
lua/metals/config.lua

refs: https://github.com/scalameta/metals/pull/5937

feat: account for new verboseCompilation setting

---

doc/metals.txt

This relates to some of the discussion happening in https://github.com/scalameta/nvim-metals/issues/644.

docs: add more info about LSP progress

---

README.md

docs: add in a minimal minimal example in the README

---

doc/metals.txt
lua/metals/config.lua

feat: add in new autoImportBuild setting

---

doc/metals.txt
lua/metals/config.lua

relates to https://github.com/scalameta/metals/pull/6121/

feat: add in new `defaultBspToBuildTool` user config

---

.github/workflows/ci.yml
README.md

This also updates the CI to also test on 0.10.0 and the latest nightly.

docs: update readme to mention requiring 0.10.x

---

lua/metals.lua
lua/metals/util.lua

fix: remove deprecated `find_active_client` calls

---

doc/metals.txt
lua/metals/setup.lua

As far as I could tell connecting to a remote debugger, while supported by metals, wasn't handled properly by this plugin.

Support attaching to remote debugger

---

doc/metals.txt
lua/metals/config.lua

feat: add in bloopJvmProperties

---

lua/metals.lua
lua/metals/config.lua
lua/metals/decoder.lua
lua/metals/doctor.lua
lua/metals/handlers.lua
lua/metals/jvmopts.lua

This reverts commit fe6125f633c1b2f68d468a2041e81e2e5e8933d4.

Revert "chore: get rid of some deprecations"

---

lua/metals/install.lua

This is just a piece of getting rid of Plenary.

refactor: use vim.system instead of Plenary.Curl
