- README.md
- doc/metals.txt
- lua/metals.lua
- lua/metals/util.lua
- nvim-lsp.vim
The default `root_patterns()` function that nvim-lsp provides
is great, but for Scala there will be times where the user
is in a situation where they have nested build files for a
workspace. By default this won't work since the client will
re-initialize causing the root workspace to be wrong. This
custom `root_patterns()` function adds in an extra check to
make sure the parent directory doesn't also have a build file.
Fixes #5
> Add in custom root_patterns.

- README.md
- doc/metals.txt
- lua/metals.lua
- nvim-lsp.vim
- plugin/metals.vim
By default `statusBarProvider` is set to showMessage.
This allows a user to override this and set it to `on`,
which enables `metals/status`. Then you can use the
newly created `metals_status` function to answer the callback
for `metals/status`, and also access the `metals_status`
global variable to use in your statusline.
Closes #3
> Add in ability to enable metals/status

- README.md
- doc/metals.txt
- nvim-lsp.vim
It used to be that you could set the diagnostic signs via global
variables, but that has switched to now having to use sign_define.
So I've changed around the examples to reflect this
> Change the examples for gutter signs.

- lua/metals.lua
- lua/metals/util.lua
- nvim-lsp.vim
- plugin/metals.vim
WIP new-scala-file. Still needs some polishing but this is a working new-scala-file command.
> new-scala-file command

- doc/metals.txt
The duplicate breaks vim help tag generation.
> Remove duplicate help tag

- lua/metals.lua
I have no lua experience, so maybe this is not actually the right thing
to do. The current implementation breaks with "attempt to call field"
though, and to me it looks like `execute_command` does not come from
`M`.
> Call the correct execute_command function

- lua/metals.lua
- lua/metals/setup.lua
- nvim-lsp.vim
This adds did focus but I see metals throwing exceptions when a notification is sent, the server recovers so we can simply remove the error printing in nvim-metals and merge, though at the moment I don't see the focus refresh being useful, when save event works for evaluations. 
It is rebased on top of decoration_provider PR
> Did focus provider

- lua/metals/setup.lua
- nvim-lsp.vim
Since https://github.com/scalameta/metals/pull/1837 we no
longer need to do the on_init hack since we explicitly
say to clients that we want on save events.
> Remove no longer needed on_init hack

- doc/metals.txt
- lua/metals/diagnostic.lua
This is a working first stab at the problem of workspace wide diagnostics in nvim-metals.
The very simple approach is to fill the quickfix-list with the LSP diagnostics for all the buffers.
It has the issue of updating it with newer diagnostics, to refresh we need to call the function again,
mapped as OpenAllDiagnostics.
As diagnostics are published per file, and not batched in a compilation, refreshing when we get a LspDiagnosticsRefresh event is probably too noisy and can be too disruptive when we are doing other things with the quickfix, e.g. going through grep.
We could think about only refreshing when the quickfix is open and keep an lsp diagnostic change ticket to check when the refresh gets called automatically. Also, we could enable some filtering to only show bloop diagnostics, …
> MVP for showing all LSP buffer diagnostics in the quickfix

- README.md
- doc/metals.txt
- lua/metals/handlers.lua
- lua/metals/setup.lua
- lua/metals/util.lua
Since this isn't part of the upstream LSP implementation yet (see here: https://github.com/neovim/neovim/issues/11710), I figured I'd give this a shot with just adding it in here first. If this seems to work well I'll try to upstream this. This is quite important to have since Metals makes heavy use of this.
> Implement basic `window/showMessageRequest`.

- README.md
- doc/metals.txt
- lua/metals.lua
- lua/metals/setup.lua
- lua/metals/util.lua
This adds in the support to send settings via `workspace/didChangeConfiguration`.
At the moment this is only sent right after the initialize. This also adds in a default
empty config table for the user to use if they are editing any settings. They can
require this like so:
```lua
require'metals'.bare_config
```
The logic internally to handle merging tables is also improved which makes
the way all of the config values are created much simpler.
All docs are also updated with the new examples and all available settings.
> Add in support for settings.

- README.md
- doc/metals.txt
- lua/metals/handlers.lua
As of https://github.com/neovim/neovim/pull/13641 this is now
in neovim core. So there is no need for the custom one that we
have in here anymore.
> Remove showMessageRequest.

- README.md
- doc/metals.txt
One thing I did wrong with coc-metals was duplicate the stuff
I put on the website and in the readme. I don't want to make that
mistake again with having docs in various places. In this commit
I slim down the readme and point people to the help docs and also
to the example configuration in the discussions. I would like to
keep the readme as thin as possible while keeping the help docs
as rich as possible and the center of truth. This will bring the
most benifit since you can both view them on github and also
while in neovim.
> Trim down readme and point to help docs.

- lua/metals/setup.lua
In order to make sure Metals will work in any scenario, this small
change just grabs the parent directory of the opened file if it can't
find any of the root patterns.
Closes #66
Relates to https://github.com/scalameta/metals/issues/2384
> Default to parent directory if opening a single Scala file.

- .luacheckrc
- lua/metals.lua
Fixes #87 
~I haven't installed everything from CONTRIBUTING.md, just~ want to check if approach makes sense :) 
I'm doing it this way because I couldn't find an API that parses `term://{cwd}//{pid}:{cmd}` format that is in buffer name for terminals.
If there's such an API (and if it's preferable to use it), let me know @ckipp01
> Set buffer-local variable to identify metals logs buffer

- doc/metals.txt
- lua/metals.lua
- lua/metals/health.lua
- lua/metals/messages.lua
- lua/metals/setup.lua
Up until this point nvim-metals fully handled the Metals install and
updates, and there was no option to _not_ have it do so. By adding in
this setting users can now just set `g:metals_use_global_executable` to
true, and then nvim-metals will default to using whichever Metals
executable is found on the $PATH.
NOTE: That this isn't really recommended to use as most of the time it's
preferable to just let nvim-metals handle this, but if you're in the
group of Nix users or someone that wants to use the same executable for
multiple different clients, this can be useful to you.
> Add in a g:metals_use_global_executable option.

- lua/metals/log.lua
If not in the situaton where a user open a Scala project for the very
first time without the cache dir every being created, it will throw a
warning. This is because we are trying to log before we've installed
Metals which is when the cache dir was created before.
> Ensure nvim-metals cache dir is created right away.

- lua/metals/setup.lua
If you do `:help lsp.start_client`, you can find the definition of the `on_attach` callback, which takes two parameters. For instance when using `lsp-status`, one need to pass the parameters to `require('lsp-status').on_attach` for it to initialize properly.
> Pass client and bufnr parameter to user on_attach function

- lua/metals/setup.lua
As a follow-up to https://github.com/scalameta/metals/pull/2615, color
can now be disabled for DAP communication to avoid all the color codes
that were showing up both for Bloop and sbt.
Closes #107
> Disable color output for DAP via init option.

- lua/metals.lua
The latest nvim snapshot got rid of _trim_and_pad and replaced it with _trim.
Users will need to update to the latest snapshot.
> Update to _trim.

- doc/metals.txt
- lua/metals.lua
- lua/metals/setup.lua
- plugin/metals.vim
The original idea behind this is for the workflow I have of:
1. publishing Metals
2. re-bootstapping Metals with `:MetalsInstall`
3. Wanting to then test those changes without having to close and
re-open nvim.
This adds in a new `:MetalsRestartServer` which will allow for me to do
just that. Also, it adds in a `:MetalsStartServer` in the case that a
user is using this for the first time and installs Metals. To get
started they used to have to close and reopen, but now after the initial
install they can just use the new `:MetalsStartServer` command.
Closes #118
> Add in ability to restart server.

- doc/metals.txt
- plugin/metals.vim
This was sort of left over from when I just started the plugin and was
also creating extra LSP helper commands. This is the last one left that
I sort of just forgot about, and it probably just shouldn't be in here.
All it's doing is just calling `vim.lsp.buf.formatting()`, so it can
very easily be mapped locally. Plus most people may already have this
mapped directly calling that anyways.
Plus, is is also conflicting with another plugin:
https://github.com/mhartington/formatter.nvim/issues/35
> Remove `:Format` command.

- doc/metals.txt
- lua/metals.lua
- lua/metals/setup.lua
This will allow a user to set this to block Metals from starting by
default all of the time when they may not want it to.
Still not 100% sure on this as I think it may be annoying to have to manually do this for a workspace that you do want to have regularly enabled. So one thing I'm thinking about it is to just create a file at the workspace root, like `.metals/nvim-metals.txt` and if that file exists, then even if the user has the `metals_disabled_mode` set to `true`, it would still start in that workspace. If anyone out there is planning on using this, lemme know your thoughts.
Closes #119 
For now, I'm just going to leave this as if. If someone actually uses it and like it and they get annoyed by having to manually do it in the same workspace all the time, we can adjust and enhance …
> Add in a `metals_disabled_mode` option.

- doc/metals.txt
- lua/metals/diagnostic.lua
- lua/metals/setup.lua
NOTE: This does break the existing mappings. For example you no longer
have a `metalRunType` key in your configuration table, but now you have
a full `metals` table. So before you would have had something like:
```lua
{
type = "scala",
request = "launch",
name = "Run",
metalsRunType = "run"
},
```
Where now you'll want to replace the `metalsRunType` with a `metals` key
and a `runType` key in the `metals` table. For example:
```lua
{
type = "scala",
request = "launch",
name = "Run",
metals = {
runType = "run"
}
},
```
This also adds in some new keys:
```
args = { "firstArg", "secondArg", "thirdArg" },
jvmOptions = {},
env = {},
envFile = "",
```
All of these can be set in the `metals` table.
Closes #129
> Add in the ability to pass in other args to the DAP process

- lua/metals/diagnostic.lua
When you call open_all_diagnostics it used to still open up if there
were no diagnostics, but this changes the behavior now that if there are
no diagnostics left it just closes the qf list.
Closes #133
> Close qf window when no diagnostics left.

- doc/metals.txt
- lua/metals/handlers.lua
The main reason we had our own `textDocument/hover` in here was due to the
default one not wrapping. This caused some issues with type signatures that were
quite long and not being able to see the whole thing. Now due to the improvements
in https://github.com/neovim/neovim/pull/14649 we can just remove our since the
default one now wraps.
> Remove our `textDocument/hover` implementation.

- lua/metals/decoration.lua
This was removed from NeoVim, so we need to switch to directly
use `open_floating_preview`.
> Remove usage of fancy_floating_markdown.

- README.md
- Consistent Neovim
- changed `master` branch reference to `main`
- `shortmess` setup for lua
> fix readme with main branch and Neovim typo

- CONTRIBUTING.md
- lua/metals.lua
Refactor metals.lua:
- simplified M.new_scala_file
- used fn variable instead of vim.fn
- fixed new_scala_file documentation link
- fixed typo `Parameters`
- (optional) set parameters name for `execute_comand` in `M.super_method_hierarchy`
CONTRIBUTING.md
- fixed typo in CONTRIBUTING.md
> refactor metals.lua for new_scala_file

- lua/metals/commands.lua
Metals command names are normalized, so command starts with a verb and is followed by a noun.
I understand that we want to mimic Metals commands, but at least we can make them more structured.
Completely optional PR :)
> Normalised command names: verb + noun

- CONTRIBUTING.md
- doc/metals.txt
- lua/metals.lua
- lua/metals/commands.lua
- lua/metals/decoration.lua
- lua/metals/setup.lua
I was curious about neovim commands misalignment you mentioned on Twitch, so I decided to experiment.
Everything seems to work and looks now more mature.
What do you think about this change?
Changes:
- Fixed typo `luacheck`
- Fixed typo for `MetalLogToggle` ( missing `s` after Log ) ( changed later to `MetalsToggleLogs` )
- Fixed typo for `MetalsDoctor` in documentation and changed to `MetalsRunDoctor`
- Changed neovim Metals command in the way where the verb is followed by a noun
- Reflected commands changes in documentation
- checked format and lint
- Sorted metals telescope commands alphabetically
- Fixed `frop` typo in `analyze_stacktrace`
- Renamed `worksheet_hover` to `hover_worksheet` command
- Sorted Commands in docs
- Sorted LUA API commands in docs
- Added support for previous …
> Align Metals neovim commands with Metals Telescope commands

- lua/metals/setup.lua
This makes sure Metals doesn't attach to buffers that are opened up by
plugins like Fugitive where nvim-metals still thinks it's a Scala file,
but really shouldn't attach to it.
Fixes #181
> Ensure Scala file is a valid scala file.

- doc/metals.txt
- lua/metals.lua
- lua/metals/setup.lua
This will allow for a user to easily use a mapping to toggle a boolean
setting. Thinking about this a bit more, we can probably in the future
make a nice way to change any setting value and send that in. Something
that prompts the user for input, and then they can input the new value
and the same logic could be used to send in the notification to Metals.
But until we need that, this should be fine.
Closes #189
Pinging @stumash since you were the one to bring this up.
> Add in ability to toggle boolean settings.

- doc/metals.txt
- lua/metals/setup.lua
Originally these were set to make the onboarding experience a little
easier for users that wanted to give out the built-in LSP a try in
Neovim. However, as more users have adopted this now and more people
are setting these settings for other servers, you don't want them
duplicated. So I've gone ahead and moved the followig:
```
autocmd CursorHold  <buffer> lua vim.lsp.buf.document_highlight()
autocmd CursorMoved <buffer> lua vim.lsp.buf.clear_references()
autocmd BufEnter,CursorHold,InsertLeave <buffer> lua vim.lsp.codelens.refresh()
```
If you still want code lenses and document highlights to work as
expected, you'll need to add these autocmds to your local config.
Closes #195
> Remove non metals-specific autocmds. (Changes needed in your local config)

- lua/metals.lua
These have been deprecated now for a while, so I think we're
safe to remove them.
> Remove deprecated functions.

- README.md
- doc/metals.txt
It used to be that the message requests weren't being shown with Neovim
without this being removed since our autocmd relies on a filetype.
However this seems to be working now without removing it both on nightly
and on 0.5.0 stable.
Fixes #193
> Remove the recommendation to Remove -F from shortmess.

- doc/metals.txt
- lua/metals/jvmopts.lua
- lua/metals/setup.lua
- lua/metals/util.lua
Unlike some of the other Metals clients, up until this point it's been
pretty much impossible to set server properties for Metals. This change
adds in a new `serverProperties` setting that allows you to send in
properties that Metals will be started with.
This also uses https://github.com/ckipp01/nvim-jvmopts to grab the
values from the workspace `.jvmopts` file and also values from
`JAVA_OPTS` and `JAVA_FLAGS`. However, nvim-metals strips out most of
the settings from these if they are related to memory. Mainly because
the memory requirements you put in your workspace are more than likely
for sbt, not for metals. Instead use `serverProperties` for this. I do
this to align with coc-metals and the VS Code extension.
> Add in ability to specify serverProperties and also grab javaopts.

- README.md
- doc/metals.txt
So the main reason we need this is because nvim-metals adds in some extra
logging and messages to help users get started. So for example say you try
to get started but haven't actually installed Metals, it will log and give instructions
to you about how to do that. However, without removing -F, this won't happen.
So you can remove this if you're confident you don't need it and everything
will work fine, you just might not get messages about things going wrong.
Closes #193 for real this time.
> Revert commit about removing -F recommendation.

- lua/metals.lua
Sets the filetype to `log`.
Resolves question here: https://github.com/scalameta/nvim-metals/discussions/207#discussioncomment-1248434
> Add syntax highlight to the log when running `:MetalsToggleLog`

- doc/metals.txt
- lua/metals/setup.lua
In the last release of metals there were some massive improvements
to the speed of this feature. This used to be turned off due to
performance issues, which we no longer need to worry about.
> Set superMethodLensesEnabled to default to on.

- doc/metals.txt
- plugin/metals.vim
The naming layout for the diagnostic signs has changed:
https://github.com/neovim/neovim/pull/12655
> Fix display of diagnostic signs

- lua/metals/setup.lua
This just ensures that users can correctly set compilerOptions in the
initializationOptions that are sent to Metals. I guess no one uses these
ha, since this could never have worked before unless they user would set
it to `{}` first and then set the value they were wanting. However, I'm
assuming that's never been done. I realized this while looking at
https://github.com/scalameta/metals-feature-requests/issues/235
> Ensure bare_config can set compilerOptions.

- lua/metals/setup.lua
When we added in the new settings for serverProperties we forgot
to add a check for them and sort of just assumed that everyone would
be starting with the bare_config. However, that's not the case, and this
fails if you just pass in `{}`.
Closes #242
> Ensure an empty config can still be used

- .gitignore
- CONTRIBUTING.md
- Makefile
- lua/metals/rootdir.lua
- tests/setup/clone_spec.lua
- tests/tests/root_dir_spec.lua
Interesting, this fails when you give it both `.scala` and `.git`, but not if you give it `.git`. Something odd with the ordering is going on here I assume.
> Add test for detecting root dir when non root

- doc/metals.txt
- lua/metals.lua
- lua/metals/commands.lua
This is to go along with https://github.com/scalameta/metals/pull/3284
since in the last release the arguments needed for these commands
changed from the customer ones to just use `TextDocumentPositionParams`.
> fix: update arguments to be sent in with super method commands.

- doc/metals.txt
Add in an example showing the newly added `runOrTestFile` in https://github.com/scalameta/metals/pull/3311.
> Add in new runOrTestFile example

- doc/metals.txt
- lua/metals/config.lua
- lua/metals/install.lua
- lua/metals/messages.lua
- lua/metals/version.lua
- tests/setup/install_spec.lua
- tests/tests/version_spec.lua
This makes several different changes.
1. Introduces a new way to set the version to the latest snapshot. Instead of always
having to find the latest snapshot and manually set it, we instead pull it from the
maven-metadata.xml file and automaticaly use that. There has been issues in the past
with this not syncing as fast as you want, so it's not bullet-proof but should work
for most use cases. To use this just set your serverVersion as `SNAPSHOT`.
Closes #122
2. Starts work on #234. Not the preferred way to set your serverVersion or serverOrg
is to set it in the metals settings table, not as options.
> Add in the ability to automatically install latest snapshot.

- doc/metals.txt
- lua/metals.lua
- lua/metals/config.lua
- lua/metals/install.lua
- lua/metals/messages.lua
- lua/metals/setup.lua
This is now the preferred way to set these instead of using the
`g:metals_use_global_executable` and `g:metals_disabled_mode` options.
Closes #234
> Add in disabledMode and useGlobalExecutable settings to the config table

- .github/workflows/ci.yml
- README.md
- doc/metals.txt
- lua/metals.lua
- lua/metals/handlers.lua
- lua/metals/tvp/init.lua
- lua/metals/util.lua
NOTE: That when this pr is merged, 0.6 will be the new required default for `nvim-metals`.
So we ended up not being able to use `vim.ui.select` where I thought we'd be able to. It's not recommended to use it in places were a return value is needed since it's call back based. The tricky part is that the default implementation in core is blocking, so it will work here, but then when you using an async plugin like telescope, it won't work. Since it's not safe to use that there we don't use it. Same goes with `vim.ui.input` in places where a return values us needed, like in a LSP server request.
> Update all the things for 0.6

- doc/metals.txt
- lua/metals/setup.lua
Thanks to https://github.com/mfussenegger/nvim-dap/pull/376 the timeout
can now be customized. The default in nvim-dap is 4 seconds, which is
just too short with Metals. This will avoid the warning being shown all
the time. This isn't configurable for the time being, but if it needs to
be in the future it can be.
> feat: bump initialize_timeout_sec to 10

- lua/metals.lua
- lua/metals/decoration.lua
- lua/metals/doctor.lua
This was removed on HEAD. Seems to work exactly the same without it both
on HEAD and also 0.6.0
> fix: remove usage of lsp.util.close_preview_autocmd()

- lua/metals/config.lua
- lua/metals/install.lua
- lua/metals/util.lua
I propose a small fix for now, it will check if both metals.bat and cs.bat are on the path and uses them. It should work.
Both metals and coursier execs should be configurable and have different default values on win/linux.
> Fix Windows path, support .bat files

- README.md
- lua/metals/config.lua
- lua/metals/messages.lua
Hi here is my quick fix for the problem I reported 2 days ago in https://github.com/scalameta/nvim-metals/pull/297.
I could not see the backslashes in the path in the error message so I left it with normal slashes.
> Improves Coursier setup documentation and error reporting on Windows.

- lua/metals/config.lua
This just moves things around a bit. Previously we would log the windows
message, but then also again log the generic coursier message. We don't
need to do both and this makes it so we don't need to do two logs, but
rather include the windows message in the other warnings if metals or
coursier isn't found.
> refactor: ensure windows warning gets shown with others.

- lua/metals.lua
This changed upstream and is no longer worksheet but scala-worksheet.
Closes #311 
I'll probably wait to merge this as it will break for users that aren't on nightly.
> fix: fix the quick worksheet command

- lua/metals.lua
- lua/metals/handlers.lua
this fixes the `MetalsOrganizeImport` command in neovim nightly.
Here is the corresponding breaking change announcement: https://github.com/neovim/neovim/issues/14090#issuecomment-1012005684
> Explicitly pass character offset encoding to `apply_workspace_edit`

- lua/metals.lua
- lua/metals/commands.lua
- lua/metals/decoder.lua
This uses the new `list-build-targets` that is going to be introduced in
https://github.com/scalameta/metals/pull/3649. This might change a bit
yet, but this is roughly what will be needed to use this.
> feat: Add in functionality to get build target info.

- lua/metals.lua
- lua/metals/config.lua
- lua/metals/handlers.lua
- lua/metals/install.lua
- lua/metals/status.lua
- lua/metals/util.lua
I'm going to probably play around with this for a while to see if I like
it before merging, but the idea here is that in situations where
something goes wrong it might be hard to tell because you only get the
small status message. Now you'll actually get a select that will show
you the tooltip and the command if there is one, or it will just warn
you of what the tooltip says.
Fixes #102
> feat: take into account tooltip and command in metals/status

- lua/metals.lua
- lua/metals/doctor.lua
There are places where we are using it where we don't need to since it'd
error already in metals.lua if it was an issue.
> refactor: clean up pcall usage

- doc/metals.txt
- lua/metals/install.lua
- tests/setup/install_spec.lua
Now that this value can be obtained by just looking at the
https://scalameta.org/metals/latests.json file, it makes doing this much
more robust.
fixes #122
> feat: introduce a latest.snapshot value for serverVersion.

- lua/metals/install.lua
- tests/setup/install_spec.lua
If not, this blocks the UI when installing and doesn't let the
metals/status be updated. This change only blocks now in tests.
> refactor: go back to passing in a sync flag for install

- lua/metals/install.lua
This shouldn't take long at all, but I noticed at times if you are
fetching the latest snapshot version there might be a slight pause, so
this just adds a status message to notify the user what is going on.
> refactor: add a status message when fetching snapshot

- lua/metals/doctor.lua
Version 3 of the doctor format adds in some nice structured goodies in
the header instead of a big string. For example now we also get the jdk
version, the metals version, the bloop version, etc all nicely displayed
for the user. We also kept in logic to ensure that users on old metals
can still use the doctor without stuff blowing up
> feat: account for version 3 of doctor

- README.md
- doc/metals.txt
- lua/metals/config.lua
- lua/metals/doctor.lua
This is a breaking change. If you see error messages related to autocmds
after updating this you'll want to ensure that you're on the newly
released 0.7.0 of Neovim.
- https://github.com/neovim/neovim/releases/tag/v0.7.0
The diff in this commit will give you a good idea of how to migrate the
old style of autocmds to the new style.
Closes #347
> feat!: utilize new autocmd api

- lua/metals/config.lua
- lua/metals/doctor.lua
This was screwing up the initialize or attach locally if you had that
autogroup also called nvim-metals since it would clear it due to the
ones internally having the same group name.
> fix: make autogroup names unique

- lua/metals/install.lua
- tests/setup/install_spec.lua
Now that the new Metals version is out latest.snapshot and latest.stable
should both default to the 2.13 artifacts since that's what metals is
publishing.
> refactor: default to 2.13 for latest.snapshot and latest.stable

- lua/metals/handlers.lua
I was still using the old signature for this which ended up using the
bufnr to set the encoding causing it to blow up.
refs: #382
> fix: Fix signature for locations_to_items

- lua/metals.lua
Since it's common to probably use this when you're inside of a .conf
file, Metals won't actually be attached to the current buffer, which
will cause this to just do nothing. So instead of using 0, we'll always
search and use a valid metals buffer.
fix #382
> fix: Ensure find in dependency jars is always using a valid buf

- Makefile
- neovim.toml
- tests/tests/handlers/quickpick_spec.lua
The goal will be to test all of the custom handlers for Metals. While we
probably won't be able to test the full cycle of communication with
these between server and client we can at least test the Neovim side of
things and mock what we need to. This will at least ensure that when a
specific handler is called we aren't using an old API and we can catch
changes in the loads that Metals is sending us.
This first test covers `metals/quickpick`
> test: start adding in handler tests

- lua/metals/decoration.lua
- lua/metals/handlers.lua
- tests/tests/decoration_spec.lua
Since `nvim_buf_set_virtual_text` is deprecated I figured it was time to
do a migration to the new way of dealing with virtual text using
extmarks. In some ways it's more verbose, but there are more
possiblities. This also slightly changes the behavior now with the
virtual text shifting with the lines until they are replaced. I'm not
sure I love that, but I'm not 100% sure there is an easy way to avoid
that unless we do a clear when entering insert mode. We'll see if people
complain.
This also adds in tests to cover the decorations package.
> refactor(decorations): migrate decorations to use extmarks

- lua/metals/log.lua
I have no idea how this was working before and why it breaks with
nightly, but this should fix the issues we've been seeing in CI
> fix: ensure mkdir called with parents = true

- doc/metals.txt
- lua/metals/commands.lua
- lua/metals/config.lua
- lua/metals/setup.lua
This makes a couple small changes that allows the toggle logs command to
be able to take a param to either open vertically or horizontally. It
now takes a direction of either `vsp` or `sp` with a default of `vsp`.
This also makes a small change that when we create the user commands we
pass in whether or not an arg is expected, and you can set the amount of
args in the commands table.
Closes #250
> feat: allows toggle logs to be horizontal or vertical

- doc/metals.txt
There are actually three commits on this branch:
1. The changes requested in #404 to explicitly reference `vim.api` everywhere
2. While I was in the doc I fixed some typos
3. This commit includes some formatting and language changes
I made them as separate commits so that I can back out any changes that aren't desired.
> Update help doc 

- doc/metals.txt
Add a note about requiring `metals.tvp` instead of just `metals`.
> docs(tvp): more clarity in tvp docs

- doc/metals.txt
- lua/metals.lua
- lua/metals/decoration.lua
I want to be able to override default border in hover worksheet floating window like this
`:lua require"metals".hover_worksheet {border = 'rounded'}`
I also did a little wrapper so if `hover_worksheet` is called twice than it will focus floating window (like regular `hover` behaviour). As I often find myself wanting either to scroll this floating window or to copy something from it. But I'm not sure whether you would want this in nvim-metals codebase or not.
```lua
local function hover_worksheet()
local existing_float = vim.F.npcall(vim.api.nvim_buf_get_var, 0, 'lsp_floating_preview')
if existing_float and vim.api.nvim_win_is_valid(existing_float) then
vim.cmd('call win_gotoid(b:lsp_floating_preview)')
return
end
metals.hover_worksheet { border = 'rounded' }
end
map('n', '<leader>hw', …
```
> add opts to hover_worksheet

- lua/metals/status.lua
This message steals your focus and forces the user to hit enter which is
pretty annoying. I hit on this quite a bit. This first came into play
due to us adding better support for status actions, but this is one case
that just doesn't work well in nvim. So for now, we ignore it.
> refactor: ignore status about external sources not compiling

- lua/metals/config.lua
- lua/metals/setup.lua
Since neovim 0.7 this repository changed command creation into new api `api.nvim_create_user_command`.
It thou changed it's behavior and made `MetalsNew(Scala/Java)File` unusable as it now passed empty strings instead of nil when no arguments were given. It lead to funny behaviors for optional arguments which were present in 
`local new_file = function(language, directory_uri_opt, name_opt, file_type_opt)` implementation so directory_uri_opt on metals side was `Some("")` instead of None. It threw runtime error which now is fixed and all commands arguments are now nil when they equal `""`
This change in neovim API looks like is intended according to tests:
https://github.com/gpanders/neovim/blob/0d188f718b64aacd69f61eed54f6c47a1cb08414/test/functional/api/command_spec.lua#L192
> fix empty strings as args passed always as arguments for neovim 0.7+

- doc/metals.txt
- lua/metals/tvp/init.lua
This was proposed in [this](https://github.com/scalameta/nvim-metals/discussions/279#discussioncomment-3314378) discussion. And for me this option would make tvp feature more pleasant to use.
> feat: add option to execute tvp node command on leaf toggle

- lua/metals/config.lua
This will be helpful in situations where you hit on something and want to
look at the logs, but the exception or whatever the issue was already
happened. Before this started tailing from the moment it opened.
Closes #430
> refactor: also show the last 100 lines in toggle logs

- lua/metals/config.lua
- tests/tests/config_spec.lua
NOTE: That when doing this, you're 100% on your own with how Metals gets
started. If what you pass in doesn't work, then nothing will work. Also
keep in mind that no java_opts or `config.server_opts` that you pass in
will be applied. You'll need to apply them yourself in the `cmd` table.
This isn't added to the docs because if you're sane you shouldn't do
this. This is for Anton.
> feat: allow user to override config.cmd

- doc/metals.txt
- lua/metals.lua
- lua/metals/commands.lua
- lua/metals/config.lua
These normally shouldn't need to be used, but are useful in situations
where you have scripts inside of an existing sbt or Mill build.
> feat: ensure scala-cli commands and settings are added.

- doc/metals.txt
- lua/metals.lua
- lua/metals/config.lua
- lua/metals/install.lua
- lua/metals/messages.lua
- tests/tests/config_spec.lua
Another feature that should be useful for Nix users. In the situation where
they don't want nvim-metals to control the install, but also don't want to
use a global executable, this will allow them to instead use `metalsBinaryPath`
which allows you to pass in any path.
Know that you can't use this _with_ `useGlobalExecutable`. If you do, it will take
priority and win.
Addresses #454
> feat: add in metalsBinaryPath

- README.md
As of https://github.com/neovim/neovim/pull/18251 we no longer need to ensure
that the user removes F to see the messages.
> docs: remove note about shortmess

- README.md
- lua/metals/config.lua
This is now done in core via https://github.com/neovim/neovim/pull/18847
so we can safely remove this from nvim-metals. I also realized that this
was probably breaking assumptions in the past if anyone tried to
override the `on_init` handler. Now this should work as expected when a
user tries to override.
Closes #465
> fix: remove manual didChangeConfiguration call

- doc/metals.txt
- lua/metals.lua
- lua/metals/commands.lua
- lua/metals/config.lua
- lua/metals/handlers.lua
- lua/metals/messages.lua
- lua/metals/setup.lua
- lua/metals/test_explorer.lua
Hey! 
I've been wanting to run individual tests in `nvim-metals` since forever. Finally found some time and tried to do it with test explorer.
Seems like everything is working pretty good for me. 
I added two commands:
-  One for browsing all test suites and running one of them.
- Another one for browsing test suites only in current file and running one test case from selected suite.
Bouth commands can be rerun with `:lua require'dap'.run_last()`.
In order to use it one need to edit metals config like this:
```lua
local metals_config = metals.bare_config()
metals_config.settings = {
...
testUserInterface = "Test Explorer",
}
metals_config.init_options.testExplorerProvider = true
```
Here is a small video of how it works:
https://user-images.githubusercontent.com/14187674/197073732-6696682b …
> feat: add test explorer

- lua/metals.lua
- lua/metals/decoder.lua
Instead of just using the fileUri instead of the name we give the buffer while using the decoder feature we instead can use the requestedUri that is returned with the decoded response. This is unique for each class in a file and for each build target. This way you can now view 2 different classes in the same file with no issue.
Fixes #459
> refactor: don't use file URI in decoded buffer

- doc/metals.txt
- lua/metals/test_explorer.lua
Just a small feature that I noticed I wanted right away. In the situation where there is only a single suite, don't show the select to choose that single item. Instead, just auto-choose it.
For some reason it's  not letting me assign you as a reviewer @antosha417, but just a heads up. What do you think of this?
> feat: auto-select the suite when it's the only one

- lua/metals/install.lua
- tests/tests/install_version_spec.lua
This adds in a slightly more involved check to ensure the
user is getting 2.13 artifacts when the server version is
greater than 0.11.2
Fixes #481
> fix: remove string version comparison

- doc/metals.txt
- lua/metals.lua
This can be used as an alternative to the telescope extension or for non
telescope uses to have the same type of functionality using whatever the
like for `vim.ui.select`.
> feat: add a generic commands method using vim.ui.select

- lua/metals/tvp/init.lua
Previously if a user would close the TVP panel they would still get
`metals/treeViewDidChange` notifications sent from the server which
would cause it to pop open again even though the user had it closed.
This ensures that a proper `metals/treeViewVisibilityDidChange` is sent
to let Metals know it was closed.
Fixes #489
> fix: ensure close is called on BufDelete

- lua/metals/config.lua
This will help https://bleep.build/ users
> feat: add in bleep.yaml as a default root pattern.

- lua/metals/setup.lua
Closes #513. Allows specification of `mainClass` in debug configurations. Example:
```lua
require("dap").configurations.scala = {
{
type = "scala",
name = "Debug with explicit main class",
request = "launch",
metals = {
mainClass = "com.foo.App",
},
},
}
```
I've tested this locally and it works as I would expect it to.
> feat: pass mainClass in DAP request

- doc/metals.txt
- lua/metals/config.lua
I recently used `:LspLog` and really liked how it opened in a new tab. I
feel like this is the way to go instead of trying to do a `sp` or `vsp`.
This pr changes `toggle_logs` to now no longer take a direction, but to
instead just open a new tab.
> refactor: change toggle_logs to open a new tab

- tests/tests/handlers/execute_client_command_spec.lua
Nightly changed this yet again, so we'll no longer get the
'No diagnostics set' message, but the window also still won't
open. So this change actually creates a diagnostic for the window
to ensure that when the metals-diagnostic-focus comes it, it opens
up.
> fix(test): ensure diagnostic focus test works

- lua/metals.lua
The telescope - organize imports command doesn't work for me when I also have null-ls setup with the gitsigns integration. The problem seems to be twofold:
1. All language servers are sent `textDocument/codeAction` when formatting
2. When executing the responses to 1., I think the wrong object is passed to `vim.lsp.buf.execute_command`
I tried replacing `lsp.buf.execute_command(result.command)` with `lsp.buf.execute_command(result)`, which did make stuff happen when I ran "Organize imports", but my buffer ended up empty. Not really sure how the different actions interact to make that happen :sweat_smile: 
So I tried limiting the "Organize imports" command to only send the request to the metals language server. That seems to have fixed it.
-----------
I have very little experience with …
> Only send codeAction to metals when organizing imports

- lua/metals/config.lua
Instead of relying on `.metals/metals.log` we now grab the actual root
uri from the config cache and use that to put together the location that
the logs file should be at. This will ensure that no matter where you
toggle the logs from or where you open the project from that we are
always looking in the right place.
Fixes: https://github.com/scalameta/nvim-metals/issues/530
> refactor: use the actual root in config cache for toggle logs 

- doc/metals.txt
- lua/metals.lua
- lua/metals/commands.lua
This will add in the following:
- `:MetalsOpenNewGithubIssue`
- `open_new_github_issue()`
which both are a command to grab some info locally and create a new
issue with it in the Metals github repo.
> feat: add in new commands to create github issues

- lua/metals/messages.lua
- lua/metals/tvp/init.lua
This will hopefully give the user a bit more information about what is
happening when they receive a `null` from the tree view. Since it's not
supported yet in Scala 3 this may happen. So in that situation we tell
them that and also let them know that if they are in Scala 2 they should
create an issue. We also better catch the situation where they truly get
a view id that isn't supported. In that case we show them what id it is.
Closes #546
> refactor: make error for null in reveal in tree better

- lua/metals.lua
- lua/metals/doctor.lua
I noticed recently when doing a `:MetalsInfo` that you could edit the
window. This isn't needed or desired. This changes make sure that both
the info and the doctor windows are marked as readonly.
> fix: make sure floats are marked as readOnly

- doc/metals.txt
- lua/metals.lua
- lua/metals/commands.lua
Addresses https://github.com/scalameta/nvim-metals/issues/551
`restart_server` is renamed to `restart_metals`
`restart_build` is renamed to `restart_build_server`
> Better "Restart X" command names

- lua/metals/install.lua
- tests/setup/install_spec.lua
- tests/tests/install_version_spec.lua
This allows me to get rid of some of the hacky stuff I was doing to
compare versions to know if we should be pulling 2.12 or 2.13.
> refactor: start using lua-version api

- lua/metals/handlers.lua
Currently when we would get a `value` inside of the inputBox params we
didn't use it as the default when we could have been.
> fix: use the default value in metals/inputBox

- lua/metals/config.lua
As of 34a82230 we added in a check to get the version out of the release
file. Now we also make sure that the file actually exists before doing
the check.
Closes #577
> fix: add a check if the release file exists

- doc/metals.txt
- lua/metals/config.lua
- lua/metals/rootdir.lua
- tests/tests/root_dir_spec.lua
With this change, users can now set `config.find_root_dir_max_project_nesting` to an integer if you want to override the default # of parents.
Related to discussion #584
Note: It doesn't have to use recursion, since it was already looping through a finite list of parent folders, one at a time.
Second note: I didn't write any tests since I'm not sure how to set those up. I did test it myself in my own project. **(Running `make tests` failed on my system.)** What I'd probably do is set up a folder tree like this:
testdir/
- build.sbt
- a/
- build.sbt
- b/
- build.sbt
- c/
- build.sbt
- src/main/scala/Main.scala
and set `config.find_root_dir_max_project_nesting` to values between 0 and 4, with the following expectations:
0: root_dir = `testdir/a/b/c/build.sbt`
1: root_dir = …
> Tweaked find_root_dir to accept a configurable max # of grandparents

- doc/metals.txt
Following the discussion in https://github.com/scalameta/nvim-metals/discussions/603 I have opened this PR as a reminder to myself to take of that.
I am sure that we could update the description as well but I'm wondering if this documentation is taken from elsewhere, I also need to double check if any other options/default changed in order to include the changes in that PR.
> Update doc about enableSemanticHighlighting

- lua/telescope/_extensions/metals.lua
This just changes the guard here to make sure that if the user
doesn't select anything with the telescope extension that instead
of crashing we just do nothing.
Fixes #606
> fix: avoid crash when there is no selection

- .github/workflows/ci.yml
- README.md
Previously this was testing against 0.9.0 but we now target 0.9.2 and I also added a note about supporting the latest version of 0.9.x
> chore(ci): test against 0.9.2

- lua/metals.lua
When you just opened up a project if you quickly tried to get the build
target info before importing was done, you'd get an empty table back
resulting in an empty picker, which was confusing. This just adds in a
check to ensure the table isn't empty.
> fix: don't display picker when no build targets are returned

- lua/metals/config.lua
- lua/metals/status.lua
Enables BSP status messages to be sent from the LSP server and stores them similarly to metals status text, being inside global variable "bsp_status".
In order to add it to your status line, it can be accessed by:
```lua
vim.g["bsp_status"] or ""
```
For some reason, the bsp status is not sent from the server when type is `show-message`.
> Add bsp status support

- doc/metals.txt
- lua/metals/status.lua
- tests/tests/handlers/status_spec.lua
We don't want to pollute the global namespace with this so instead of
using `bsp_status` we'll use `metals_bsp_status`.
CC @rochala .
> !fix: rename bsp_status to metals_bsp_status

- lua/metals/doctor.lua
In the new doctor short summary there is the potential to be new lines.
When adding things into the output of the doctor it was blowing up. This
ensures that these are stripped out and instead the multiple lines are
turned into a table and then added to the doctor output.
> fix: make sure new lines are taken out of the short summary

- lua/metals/decoration.lua
In theory the way we use decorations (not being an inline decoration
provider) we shouldn't hit on this and never have. However
https://github.com/scalameta/metals/issues/5843 caused me to realize
that `hoverMessage` is optional and we shouldn't assume it will always
be there. This change checks the existence of it before actually trying
to store the message to display later.
> fix: check for the existence of hoverMessage before using

- lua/metals.lua
- lua/metals/messages.lua
Currently even though the select test suite or case commands are always
available they won't actually work with Metals unless you have the Test
Explorer enabled. In order to keep discoverability of the commands I
still generate them no matter what, but if they user tries to use them,
they get a message about enabling the Test Explorer. In the past this
would just tell them, "hey, no tests", which wasn't accurate.
> refactor: include a message when Test Explorer is not set for select commands

- lua/metals.lua
I encountered this error and was a little confused by it :)
> Fix error message for organize_imports

- lua/metals/status.lua
This is causing all sorts of issues since it's appearing all the time
with messages from the BSP server or from Metals that really aren't that
useful and are often just telling the user to open the doctor. In VS
Code this isn't an issue since the pop up doesn't steal your focus and
just goes away by itself, but that's not possible to have an actionable
popup (as far as I know) in nvim, so instead we're going to just log
them.
> refactor: no longer show the statustips

- lua/metals/config.lua
I realized that we only detected build.gradle in the past and not actually build.gradle.kts as a root pattern. This could cause nvim-metals not to correctly determine the root for gradle projects.
Closes #665
> fix: account for gradle.kts

- lua/metals/config.lua
I had an error in my `on_attach` function that was causing it to silently fail before any mappings where created. There was no info at all about the failure which made it harder to understand what is happening.
This PR logs any errors that could happen during the execution of user's `on_attach` callback.
> Log and show error if user_on_attach fails

- lua/metals.lua
Instead of displaying this here, you should instead use the Metals
doctor to display this. This will remove confusion about the "supported
scala versions" that Metals dispalys which may not out of date when we
add in support for new metals version in snapshots but don't do a
release causing the help to not be updated.
> refactor: remove Metals version info from Info

- doc/metals.txt
- lua/metals/config.lua
- tests/tests/config_spec.lua
Add support for inlay hints settings introduced in Metals v1.3.0.
Reference:
- https://scalameta.org/metals/blog/2024/04/15/thalium#inlay-hints-support
- https://scalameta.org/metals/docs/editors/user-configuration
> feat: add inlay hints setting

- doc/metals.txt
I am getting an error on a duplicate tag `"not"` when generating helptags, due to the word being wrapped in asterisks here. I think it's not intended to tag on "not" here, so I've simply removed the emphasis.
> Remove emphasis on 'not' in docs

- .github/workflows/ci.yml
- lua/metals.lua
- lua/metals/tvp/init.lua
- lua/metals/util.lua
There was a change a while back that makes the buf request go to all the
attached clients. For Scala normally this isn't an issue at all, but if
you're using co-pilot which is also a client in this situation it will
fire metals requests to it which you don't want. We then throw an error
in that situation while the command still worked. This is confusing for
users, so this should fix the issue by filtering out the responses that
don't match metals.
> fix: ignore responses from other clients

- lua/metals.lua
This should also be safe for the current stable release as it checks to
see if this exists before setting it.
closes #703
> fix: make sure `make_range_params` works on nightly

- lua/metals.lua
The `execute_command` function in `lua/metals.lua` has an issue, where it ignores the response from metals in some cases and never invokes the callback even if the response returned successfully. This occurres in those cases where metals is not the only LSP client attached to the buffer (Other one was copilot in my case), and the other client gets a smaller `client_id` than metals. The `buf_request_all` notifies all clients with the requested action and the other client's response comes before metals' so the for loop exits the whole response handling because the `client_id` mismatch. 
Possible solution is to check explicitly if metals has a response (with its `client_id`) and use it to invoke the callback.
> Fix execute_command callback mechanism

- lua/metals.lua
Hello!
I recently started using the new inlay hints feature for worksheets, and I noticed that the hover window's output looks a bit strange:
I noticed that even though the hover window's syntax is set to markdown, the result itself is not wrapped in backticks, so it's just displayed as plain text.
Wrapping it makes the result display in the same way as it used to:
I'm not that familiar with lua, so if this is not the most idiomatic way to do this, I'm open for suggestions. 😄
> Fix worksheet hover output not being in markdown

- lua/metals/install.lua
This make sure that the new snapshots can be downloaded since they are now published in a new place. See https://github.com/scalameta/metals/pull/7524 for reference.
> fix: ensure new snapshots can be downloaded

- lua/metals/decoder.lua
I think this actually changed in the nvim side that this is wrapped in
an object now so we need to actually go in and get the result.
fixes #736
> fix: account for wrapped result
